/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package guia5poo.guia5;

/**
 *
 * @author LENOVO
 */
public class Galeria extends javax.swing.JInternalFrame {

    /**
     * Creates new form Galeria
     */
    public Galeria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagenShow = new javax.swing.JLabel();
        rbtnImagen1 = new javax.swing.JRadioButton();
        rbtnImagen2 = new javax.swing.JRadioButton();
        rbtnImagen3 = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(240, 240, 240));

        lblImagenShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia5poo/guia5/Img/DeathStar.jpg"))); // NOI18N
        lblImagenShow.setText("jLabel1");

        rbtnImagen1.setText("Imagen 1");
        rbtnImagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnImagen1ActionPerformed(evt);
            }
        });

        rbtnImagen2.setText("Imagen 2");
        rbtnImagen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnImagen2ActionPerformed(evt);
            }
        });

        rbtnImagen3.setText("Imagen 3");
        rbtnImagen3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnImagen3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtnImagen3)
                    .addComponent(rbtnImagen2)
                    .addComponent(rbtnImagen1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImagenShow)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(rbtnImagen1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagenShow)
                    .addComponent(rbtnImagen2))
                .addGap(34, 34, 34)
                .addComponent(rbtnImagen3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnImagen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnImagen2ActionPerformed
        // TODO add your handling code here:
        lblImagenShow.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("guia5poo.guia5.Img/Galaxy.jpg")));
    }//GEN-LAST:event_rbtnImagen2ActionPerformed

    private void rbtnImagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnImagen1ActionPerformed
        // TODO add your handling code here:
        lblImagenShow.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("guia5poo.guia5.Img/DeathStar.jpg")));
    }//GEN-LAST:event_rbtnImagen1ActionPerformed

    private void rbtnImagen3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnImagen3ActionPerformed
        // TODO add your handling code here:
        lblImagenShow.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("guia5poo.guia5.Img/nebulosa.jpg")));
    }//GEN-LAST:event_rbtnImagen3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImagenShow;
    private javax.swing.JRadioButton rbtnImagen1;
    private javax.swing.JRadioButton rbtnImagen2;
    private javax.swing.JRadioButton rbtnImagen3;
    // End of variables declaration//GEN-END:variables
}
